version: "3.8"
services:
  back:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  front:
    build: ./front
    ports:
      - "8001:8001"
    depends_on:
      - back